apiVersion: v1
kind: Service
metadata:
  name: deep-sentinel-service
  labels:
    app: deep-sentinel
  annotations:
    # Explicitly creating an Internet-facing Public Load Balancer on Azure
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: deep-sentinel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
